### ISSUE TITLE
Do you use esp-dsp?

### ISSUE THREAD

**Issue by modi12jin** [vindar/tgx#21]
@vindar Excuse me, I wonder if your library uses esp-dsp?  Any plans to use it in the future?

 I found 3D display content in the esp-dsp example, and the esp-dsp library can be directly called in the Arduino development environment

https://github.com/espressif/esp-dsp/blob/master/applications/azure_board_apps/apps/3d_graphics/README.md

**Comment by vindar** [comment]
Hi,

No, the library does not use any specific DSP instruction... I did experiment with it a little some time ago but I did not found any real improvement. Drawing 3d graphics requires mostly 4x4 vector/matrix operations which are not speed up significantly with the DSP specific instructions (in fact it was even slower in some cases because it prevented some global complier optimization/inlining).. The ESP-DSP should be more useful for 2d graphics methods (such as sprite scaling/rotation) but I have not tried to use it yet...
