### ISSUE TITLE
Compiling with STM32duino

### ISSUE THREAD

**Issue by wystewart** [vindar/tgx#26]
PC0, PC1, PC2, PC3 defined in Renderer3D.inl conflict with #define pinout definitions of the STM32.

Suggest to change to _PC0, _PC1, _PC2, _PC3.  That seems to resolve the compile issue

**Comment by wystewart** [comment]
i also added this to misc.h.  i haven't checked yet if stm32 has a native sqrt implementation.

#if ARDUINO_ARCH_STM32
    #include "Arduino.h" 
    #define TGX_ON_ARDUINO
    #define TGX_USE_FAST_INV_SQRT_TRICK
    #define TGX_USE_FAST_SQRT_TRICK     
    #define TGX_USE_FAST_INV_TRICK
#endif

**Comment by vindar** [comment]
Hi, 

Thanks for the suggestion !

I implemented the changes so hopefully it helps with STM32Duino compatibility.  Beware that the changes have been made on the `improved_drawing_primitives` branch which has many bug fixes, some speed improvement and a much better 2D drawing API  and which will become the master branch 'soon'.

As for the existence of a fast sqrt on STM32, I do not know but I suppose it is very similar to Teensy since it also use ARM Cortex-M cores so I am using the same presets for both. 

Best,
