### ISSUE TITLE
Antialiasing Lines

### ISSUE THREAD

**Issue by DIYLAB-DE** [vindar/tgx#3]
Hi,

meanwhile I use your ILI9341_T4 driver together with your tgx library and I am thrilled.
You have done incredible work - thank you very much for that!

My first module of the project is already implemented and works very well and smoothly.

I am looking for a solution that allows drawing 2D lines with smoothing. Can you maybe include antialiasing?
Of course, smoothing for circles or circle segments would be perfect, but for lines it would be enough for me.
Then the pointers would look better ;o)

Kind regards
DIYLAB (Bruno)

![ILI9341_T4_tgx](https://user-images.githubusercontent.com/87319037/125750341-9c2254c3-ec54-4732-a73f-da580c0f8c28.jpg)

**Comment by DIYLAB-DE** [comment]
Hi,

after experimenting a bit with drawing antialiased lines myself, I was able to use the drawing routine from Bodmer TFT_eSPI library with success!
He has implemented very interesting AA routines in Beta 2.4.0.
https://github.com/Bodmer/TFT_eSPI/tree/2.4.0-Beta
https://forum.arduino.cc/t/sub-pixel-anti-aliasing-on-a-tft/693082

Everything runs smoothly and I would be happy if you could implement these AA routines directly in your tgx 2D. 

It would be handy if you could adapt the routines to your color class.

Last question: Your RGB32 does not support an alpha channel - too bad. Is that difficult or impossible to implement?

Kind regards
DIYLAB (Bruno)

**Comment by vindar** [comment]
Hi, 

I did not know about Bodmer TFT_eSPI library. Thank for pointing me to this library, it seems very nice ! I just had a quick look and indeed the AA routines look good. I will try to port them to the tgx library when I have some free time. 

Concerning the RGB32 color type, it does not use its alpha channel: the A component is ignored and the color is treated as fully opaque. This is so because I wanted to make the library work with any color type (such as RGB565 and RGB24 which do not have an alpha channel). 

I do not know how feasible it will be to add alpha-blending to the drawing methods when using RGB32. I will have to think about it.

Best,

**Comment by DIYLAB-DE** [comment]
Hi,

it's really amazing what the beta 2.4.0 of Bodmer does.
By the way, you can find the AA functions for circles in the examples at the Borg Cube ;o)

Since one year I deal with the Teensy 4.x and find it strange that there are no AA libraries anywhere. You now have the chance to create something really big for the Teensy world!

I really like your tgx concept and in combination with your ILI9341 driver there seems to be no speed limits. I have already tried a lot and everything runs extremely smooth. Before I needed 50MHz to 60MHz SPI clock and regional clipping in my project to draw smoothly, now I paint everything in "image" and get no problems at 30MHz SPI thanks to your diff buffer.

By the way my compiler means to your diff buffer:

DiffBuff.cpp: In member function virtual void ILI9341_T4::DiffBuff::computeDiff(uint16_t*, const uint16_t*, int, int, bool, uint16_t)
DiffBuff.cpp: 285:13: warning: assuming signed overflow does not occur when assuming that (X + c) >= X is always true [-Wstrict-overflow]
   if (size() >= _sizebuf)
DiffBuff.cpp: 292:13: warning: assuming signed overflow does not occur when assuming that (X + c) >= X is always true [-Wstrict-overflow]
   if (size() >= _sizebuf) _stat_overflow++

To RGB32:
Just ask yourself the question - what is more important?
Continuing to paint pixelated on the display like you have for years and being "compatible" to RGB565 or taking a big step that users worldwide are eagerly waiting for?
How about an additional type RGBA32 with alpha channel?
Then it is just incompatible with the rest, but finally suitable to do big things in the project in a simple way.

You are on a very good way and the Teensy users will thank you for it!

When you have the lines in your library and are at the circles, please don't forget to consider the thickness of the circle (as in the function drawWideLine).
And circle segments would be great, then I can finally draw my scales dynamically instead of using images ;o)

You can do it - thanks!

**Comment by vindar** [comment]
Hello, 

I just made some significant improvements to the library which you may like.

1. The alpha channel for the RGB32 and RGB64 color type are now useful :-)
2. All drawing methods (for blitting as well as for drawing primitive like lines, circles, text...) now accept a second version with a signature that ends with a 'float opacity' parameter (in 0.0f and 1.0f). When such a method is called, then blending is used instead of of just copying on the Image. Furthermore, if the color type has an alpha channel, then it is used for blending (after being multiplied by the opacity factor). For color types without and alpha channel, the opacity factor is used to blend the drawing over the image background.
3. Improved methods for drawing triangles, circle and ellipses.
4. Added the drawWideLine(), drawWedgeLine() and drawDot() method from Bodmer's TFT_eSPI library for drawing wide anti-aliased lines and circles.
5. Created a companion library <a href="https://github.com/vindar/tgx-font">tgx-font</a> that contain a big collection plain and also anti-aliased fonts that can be used to draw text with tgx.  A preview of the available fonts can be found <a href="https://vindar.github.io/tgx-font/font-list.html">here</a>;

I also realized the 3D triangle rasterizer in the library could be used to do some fancy 2D effects. In particular, I plan to add methods for rotating images/sprites very efficiently (and with subpixel precision). I will also try to add anti-aliasing to other methods such as triangles and circle outline at some points...

Best,

**Comment by DIYLAB-DE** [comment]
Hi,

>I just made some significant improvements to the library which you may like.

that is much more than I hoped for, thank you very much!
You must have put a lot of time into the changes and enhancements.

My project is halfway converted to your driver and tgx and so far everything is stable.
I look forward to trying out your new features.

Thanks for your work and sharing it with us.

Kind regards
DIYLAB (Bruno)

**Comment by DIYLAB-DE** [comment]
Hi,

the first tests went extremely well - great job!!!

>I plan to add methods for rotating images/sprites very efficiently (and with subpixel precision). 

That sounds very interesting.
Then maybe I could rotate my needles in the analog module as a sprite, it's worth a try.
Maybe it's even faster than drawing the lines. 

Kind regards
DIYLAB (Bruno)
