### ISSUE TITLE
animated GIF

### ISSUE THREAD

**Issue by DIYLAB-DE** [vindar/tgx#8]
Hi Arvind,

I want to play animated .GIF and found an approach: 
https://github.com/bitbank2/AnimatedGIF

There, the examples like to use the TFT_eSPI library and the following methods:

tft.setAddrWindow
tft.pushPixels

I don't know how to implement this with your driver and tgx.
Can you help me please?

Kind regards
Bruno

**Comment by DIYLAB-DE** [comment]
Hi Arvind,

I have found a test program from Bodmer (setAddrWindow & pushPixels):

```
#include <SPI.h>
#include <TFT_eSPI.h>
TFT_eSPI tft;

void setup(void)
{
  Serial.begin(115200);
  tft.begin();
  tft.setRotation(0);
  tft.fillScreen(TFT_DARKGREY);
  tft.setAddrWindow(0, 0, 128, 128);
  tft.startWrite();
}

void loop(void)
{
  static uint32_t c = 0;
  static uint32_t dt = millis();

  uint16_t buf[32];
  uint32_t mask, val;

  for (uint16_t cnt = 128 * 4; cnt; cnt--) {
    val = random(65536) << 16 | random(65536);
    mask = 0x80000000;
    for (uint8_t i = 0; i < 32; i++) {
      buf[i] = (val & 0x80000000) ? 0xFFFF : 0x0000;
      val <<= 1;
    }
    tft.pushPixels(buf, 32);
  }

  c++;
  if (c > 99) {
    Serial.println(100.0 / ((millis() - dt) / 1000.0));
    c = 0;
    dt = millis();
  }
}
```

How would this be implemented with your libraries?

Kind regards
Bruno

**Comment by vindar** [comment]
Hello Bruno, 

I just had a quick look at the AnimatedGIF library. I think it should be fairly easy to combine it with ILI9341_T4/ TGX. Here, we are using  a memory framebuffer so all that needs to be done is to copy the scanline onto the framebuffer in the `GIFDraw()` callback and then only update the screen after `gif.playFrame()`  returns. This way there should be not flickering and other think can also be written on the screen simultaneously....

I will try to put up a example soon to combines tgx and AnimatedGIF. 

In the meanwhile, I have made some nice changes to tgx with new fancy methods , check my answer in another thread :-)

**Comment by vindar** [comment]
Hi, 

Here attached is an example on how to use the AnimateGIF library. It does not require TGX, only the ILI9341_T4 library. The DrawGIF() method is very straighforward. 

Of course, you can combine it with TGX to draw into an image instead of directly into the screen framebuffer and then you can do lots of fancy stuffs (on the fly rotation/resizing, mapping the animation as a texture on a 3D models...)

[test_AnimateGIF.zip](https://github.com/vindar/tgx/files/7092884/test_AnimateGIF.zip)

I will add the example in the library. 

Best,
